(node:*) UnhandledPromiseRejectionWarning: Error: This was rejected
    at * (*test*fixtures*promise*unhandled_promise_trace_warnings.js:*)
    at *
    at *
    at *
    at *
    at *
    at *
    at *
    at *
    at *
(node:*) Error: This was rejected
    at * (*test*fixtures*promise*unhandled_promise_trace_warnings.js:*)
    at *
    at *
    at *
    at *
    at *
    at *
(node:*) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
    at handledRejection (node:internal/process/promises:*)
    at promiseRejectHandler (node:internal/process/promises:*)
    at Promise.then *
    at Promise.catch *
    at Immediate.<anonymous> (*test*fixtures*promise*unhandled_promise_trace_warnings.js:*)
    at *
